[package]
name = "protimer"
version = "0.1.0"
description = "Time tracking for hourly engineers"
authors = ["ADYNATO LLC"]
license = ""
repository = "https://github.com/adynato/protimer"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "protimer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-log = "2"
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
rusqlite = { version = "0.31", features = ["bundled"] }
dirs = "5.0"
uuid = { version = "1.8", features = ["v4"] }
chrono = "0.4"
notify = "6.1"
lazy_static = "1.4"
printpdf = "0.7"
